formatter: markdown table

header-from: "docs/header-doc.tf"
footer-from: "docs/footer-doc.tf" 

content: |-
  {{ .Header }}

  # Usage - Module

  ## Private DNS resolver inbound endpoint
  ```hcl
  {{ include "examples/InboundEndpoint/main.tf" }}
  ```
  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}  

  {{ .Outputs }}

  {{ .Footer }}

recursive:
  enabled: true
  
output:
  file: README.md
  mode: inject

sort:
  enabled: true
  by: required

settings:
  anchor: false
  color: true
  default: false
  description: true
  indent: 2
  required: true
  type: true